# Generated by Django 4.2.7 on 2025-10-30 19:40

from django.db import migrations
from django.contrib.auth.hashers import make_password

def migrate_employee_data(apps, schema_editor):
    Employee = apps.get_model('core', 'Employee')
    CustomUser = apps.get_model('accounts', 'CustomUser')

    for employee in Employee.objects.all():
        user = employee.user
        first_name, last_name = employee.name.split(' ', 1) if ' ' in employee.name else (employee.name, '')

        CustomUser.objects.create(
            username=user.username,
            password=user.password,
            first_name=first_name,
            last_name=last_name,
            email=user.email,
            is_staff=user.is_staff,
            is_active=user.is_active,
            is_superuser=user.is_superuser,
            date_joined=user.date_joined,
            employee_id=employee.employee_id,
            position=employee.position,
            salary=employee.salary,
            department=employee.department,
            phone=employee.phone,
            address=employee.address,
            join_date=employee.join_date,
            status=employee.status,
            notes=employee.notes,
        )

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(migrate_employee_data),
    ]