# Generated by Django 4.2.7 on 2025-10-31 13:30

from django.db import migrations

def populate_submitter(apps, schema_editor):
    BillClaim = apps.get_model('core', 'BillClaim')
    Employee = apps.get_model('core', 'Employee')
    CustomUser = apps.get_model('accounts', 'CustomUser')

    for bill_claim in BillClaim.objects.all():
        if bill_claim.employee:
            try:
                employee = Employee.objects.get(id=bill_claim.employee.id)
                user = CustomUser.objects.get(username=employee.user.username)
                bill_claim.submitter = user
                bill_claim.save()
            except (Employee.DoesNotExist, CustomUser.DoesNotExist):
                pass

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_submitter_to_billclaim'),
    ]

    operations = [
        migrations.RunPython(populate_submitter),
    ]