# Generated by Django 4.2.7 on 2025-10-31 13:30

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_populate_submitter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billclaim',
            name='employee',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.AlterField(
            model_name='billclaim',
            name='submitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_claims', to=settings.AUTH_USER_MODEL),
        ),
    ]