# Generated by Django 4.2.7 on 2025-10-30 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_employee_and_make_submitter_non_nullable'),
    ]

    operations = [
    ]
