# Generated by Django 4.2.7 on 2025-10-31 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_squashed_migrations'),
    ]

    operations = [
    ]
