# Generated by Django 4.2.7 on 2025-11-06 18:29

import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_sale_status_ledgerentry'),
    ]

    operations = []
