# Generated by Django 4.2.7 on 2025-11-06 18:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_ledgerentry_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ledgerentry',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Ledger Entry', 'verbose_name_plural': 'Ledger Entries'},
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
