# Generated by Django 4.2.7 on 2025-11-07 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_sale_status'),
        ('core', '0017_ledgerentry_rebuild_table'),
    ]

    operations = [
    ]
