# Generated by Django 4.2.7 on 2025-11-22 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customer_id_sequence_and_backfill'),
        ('core', '0018_merge_20251107_1852'),
    ]

    operations = [
    ]
