# Generated by Django 4.2.7 on 2025-11-23 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_merge_20251122_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='expected_installments',
        ),
    ]
