# Generated by Django 4.2.7 on 2025-11-23 16:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_sale_expected_installments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional. Leave blank if unknown.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
