# Generated by Django 4.2.7 on 2025-12-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_inventoryitem_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='item_type',
            field=models.CharField(choices=[('inventory', 'Inventory'), ('non_inventory', 'Machine')], max_length=20),
        ),
    ]
