# Generated by Django 4.2.7 on 2025-12-19 08:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_saleitem_description_to_textfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='notes',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional. Unit purchase cost.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='item_type',
            field=models.CharField(choices=[('inventory', 'Inventory'), ('non_inventory', 'Machine')], max_length=20),
        ),
    ]
