# Generated by Django 4.2.7 on 2025-12-18 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_saleitem_description_to_textfield'),
        ('core', '0022_alter_saleitem_item_type'),
    ]

    operations = [
    ]
