# Generated by Django 4.2.7 on 2025-12-19 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_merge_20251218_1756'),
        ('core', '0023_remove_inventoryitem_notes_and_more'),
    ]

    operations = [
    ]
