# Generated by Django 4.2.7 on 2026-02-22 03:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_merge_20251219_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billclaim',
            name='attachment',
            field=models.FileField(blank=True, help_text='Allowed: PDF, images, Office documents, CSV, TXT.', null=True, upload_to='bill_attachments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'gif', 'bmp', 'webp', 'doc', 'docx', 'xls', 'xlsx', 'csv', 'txt'])]),
        ),
    ]
