# Generated by Django 4.2.28 on 2026-02-22 08:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_validate_attachment_extensions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('sale_unit', models.CharField(choices=[('pcs', 'Pieces'), ('kg', 'Kilogram'), ('ltr', 'Liter'), ('mtr', 'Meter')], default='pcs', max_length=20)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'ordering': ['product', 'identifier', 'created_at'], 'verbose_name': 'Inventory Item', 'verbose_name_plural': 'Inventory Items'},
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='minimum_stock',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='part_code',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='part_name',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='purchase_price',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='identifier',
            field=models.CharField(blank=True, help_text='Box/Drum/Batch No', max_length=50),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='inventory_type',
            field=models.CharField(choices=[('box', 'Box'), ('piece', 'Piece'), ('drum', 'Drum'), ('batch', 'Batch'), ('loose', 'Loose')], default='box', max_length=20),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='purchase_price_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='remaining_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='status',
            field=models.CharField(default='in_stock', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='unit',
            field=models.CharField(choices=[('pcs', 'Pieces'), ('box', 'Box'), ('kg', 'Kilogram'), ('ltr', 'Liter'), ('mtr', 'Meter')], default='kg', max_length=20),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='core.product'),
        ),
    ]
