# Generated by Django 4.2.28 on 2026-03-01 04:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_product_alter_inventoryitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'ordering': ['part_name'], 'verbose_name': 'Inventory Item', 'verbose_name_plural': 'Inventory Items'},
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='identifier',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='inventory_type',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='purchase_price_per_unit',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='remaining_quantity',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='status',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='minimum_stock',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='part_code',
            field=models.CharField(max_length=50, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='part_name',
            field=models.CharField(max_length=200, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional. Unit purchase cost.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional. Leave blank if unknown.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='unit',
            field=models.CharField(choices=[('pcs', 'Pieces'), ('box', 'Box'), ('kg', 'Kilogram'), ('ltr', 'Liter'), ('mtr', 'Meter')], default='pcs', max_length=20),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: (
                (lambda InventoryItem: (
                    [
                        (setattr(obj, 'part_code', f"ITEM-{obj.id}") or obj.save(update_fields=['part_code']))
                        for obj in InventoryItem.objects.filter(part_code__isnull=True)
                    ],
                    InventoryItem.objects.filter(part_name__isnull=True).update(part_name='')
                ))(apps.get_model('core', 'InventoryItem'))
            ),
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='part_code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='part_name',
            field=models.CharField(max_length=200),
        ),
    ]
