# Generated by Django 4.2.28 on 2026-03-01 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_inventoryitem_box_count_saleitem_boxes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='item_type',
            field=models.CharField(choices=[('inventory', 'Inventory'), ('non_inventory', 'Machine')], default='inventory', max_length=20),
        ),
    ]
