# Generated by Django 4.2.28 on 2026-03-02 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_item_type_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockhistory',
            name='box_quantity',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Boxes transacted', max_digits=12),
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='new_box_quantity',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='previous_box_quantity',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='part_code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Product Code'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='part_name',
            field=models.CharField(max_length=200, verbose_name='Product Name'),
        ),
    ]
