# Generated by Django 4.2.28 on 2026-03-02 05:46

from django.db import migrations


def populate_box_quantities(apps, schema_editor):
    """Migrate box data from quantity field to box_quantity field for existing entries"""
    StockHistory = apps.get_model('core', 'StockHistory')
    
    # Find all entries with "(boxes)" in the reason
    box_entries = StockHistory.objects.filter(reason__contains='(boxes)')
    
    for entry in box_entries:
        # The box count is currently in the quantity field
        entry.box_quantity = entry.quantity
        entry.previous_box_quantity = entry.previous_quantity
        entry.new_box_quantity = entry.new_quantity
        # Clear the unit quantity fields
        entry.quantity = 0
        entry.previous_quantity = 0
        entry.new_quantity = 0
        entry.save()


def reverse_populate_box_quantities(apps, schema_editor):
    """Reverse the migration - move box data back to quantity if needed"""
    StockHistory = apps.get_model('core', 'StockHistory')
    
    box_entries = StockHistory.objects.filter(reason__contains='(boxes)')
    
    for entry in box_entries:
        # Move box data back to quantity field
        entry.quantity = entry.box_quantity
        entry.previous_quantity = entry.previous_box_quantity
        entry.new_quantity = entry.new_box_quantity
        # Clear box fields
        entry.box_quantity = 0
        entry.previous_box_quantity = 0
        entry.new_box_quantity = 0
        entry.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_stockhistory_box_quantity_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_box_quantities, reverse_populate_box_quantities),
    ]
