# Generated by Django 4.2.28 on 2026-03-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_populate_box_quantities'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleIdSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('sequence_num', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Sale ID Sequence',
                'verbose_name_plural': 'Sale ID Sequences',
            },
        ),
    ]
