# Generated by Django 4.2.28 on 2026-03-09 08:04

from django.db import migrations
from django.utils import timezone


def migrate_sale_numbers(apps, schema_editor):
    """
    Migrate existing sale numbers from S-YYYYMMDD-{hex} to {DD-MM-YYYY}-FE-{serial:04d} format.
    Maintains order of creation and assigns sequential numbers per date.
    """
    Sale = apps.get_model('core', 'Sale')
    SaleIdSequence = apps.get_model('core', 'SaleIdSequence')
    
    # Get all sales ordered by creation date
    sales = Sale.objects.all().order_by('created_at')
    
    # Track sequence numbers per date
    sequence_tracker = {}
    
    for sale in sales:
        # Extract date from created_at
        sale_date = sale.created_at.date() if hasattr(sale.created_at, 'date') else sale.created_at
        formatted_date = sale_date.strftime('%d-%m-%Y')
        
        # Get current sequence counter for this date
        if sale_date not in sequence_tracker:
            sequence_tracker[sale_date] = 0
        
        sequence_tracker[sale_date] += 1
        serial = sequence_tracker[sale_date]
        
        # Generate new sale number
        new_sale_number = f"{formatted_date}-FE-{serial:04d}"
        
        # Update the sale
        sale.sale_number = new_sale_number
        sale.save(update_fields=['sale_number'])
    
    # After updating all sales, set the final sequence counters to the maximum for each date
    for sale_date, final_serial in sequence_tracker.items():
        SaleIdSequence.objects.update_or_create(
            date=sale_date,
            defaults={'sequence_num': final_serial}
        )



def reverse_migrate_sale_numbers(apps, schema_editor):
    """
    Reverse migration: restore old sale number format (not practical, so this is a no-op).
    In a real scenario, you would need to store the old values separately.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_add_saleidsequence_model'),
    ]

    operations = [
        migrations.RunPython(migrate_sale_numbers, reverse_migrate_sale_numbers),
    ]
