# Generated by Django 5.2.7 on 2026-03-12 00:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_consolidate_sale_sequence_global'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPaymentBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_ref', models.CharField(editable=False, max_length=60, unique=True)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('card', 'Card'), ('cheque', 'Cheque'), ('other', 'Other')], default='cash', max_length=30)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customer_payment_batches', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_batches', to='core.customer')),
            ],
            options={
                'verbose_name': 'Customer Payment Batch',
                'verbose_name_plural': 'Customer Payment Batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerPaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='core.customerpaymentbatch')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_payment_allocations', to='core.sale')),
                ('sale_payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_allocation', to='core.salepayment')),
            ],
            options={
                'verbose_name': 'Customer Payment Allocation',
                'verbose_name_plural': 'Customer Payment Allocations',
                'ordering': ['id'],
            },
        ),
    ]
