# Generated by Django 4.2.28 on 2026-04-15 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_allow_cascade_delete_customer_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpaymentallocation',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_payment_allocations', to='core.sale'),
        ),
    ]
