# Generated by Django 4.2.28 on 2026-04-15 07:00

from django.db import migrations
from decimal import Decimal


def populate_unit_prices(apps, schema_editor):
    """Populate missing unit_price values with purchase_price or 0"""
    InventoryItem = apps.get_model('core', 'InventoryItem')
    
    # Find all inventory items with NULL unit_price
    items_without_price = InventoryItem.objects.filter(unit_price__isnull=True)
    
    count = 0
    for item in items_without_price:
        # Use purchase_price if available, otherwise default to 0
        if item.purchase_price:
            item.unit_price = item.purchase_price
        else:
            item.unit_price = Decimal('0.00')
        item.save(update_fields=['unit_price'])
        count += 1
    
    if count > 0:
        print(f"Populated unit_price for {count} inventory items")


def reverse_populate_unit_prices(apps, schema_editor):
    """Reverse: set unit_price back to NULL for items that were backfilled with 0.00"""
    InventoryItem = apps.get_model('core', 'InventoryItem')
    
    # Only revert items that have unit_price=0.00 and no purchase_price
    # This is conservative to avoid data loss
    items_to_revert = InventoryItem.objects.filter(
        unit_price=Decimal('0.00'),
        purchase_price__isnull=True
    )
    
    for item in items_to_revert:
        item.unit_price = None
        item.save(update_fields=['unit_price'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_change_customerpaymentallocation_sale_to_cascade'),
    ]

    operations = [
        migrations.RunPython(populate_unit_prices, reverse_populate_unit_prices),
    ]
