# Generated by Django 4.2.28 on 2026-04-15 07:05

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_populate_unit_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='unit_price',
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text='Unit selling price.',
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
