# Generated by Django 4.2.28 on 2026-04-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_supplier_supplierpurchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierpurchase',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
    ]
