# Generated by Django 4.2.28 on 2026-04-17 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_supplierpurchase_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierpurchase',
            name='quantity',
        ),
    ]
