# Generated by Django 4.2.28 on 2026-04-19 06:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_remove_supplierpurchase_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentry',
            name='source',
            field=models.CharField(choices=[('sale_payment', 'Sale Payment'), ('expense', 'Expense'), ('supplier_payment', 'Supplier Payment'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.CreateModel(
            name='SupplierPurchasePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(editable=False, max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('method', models.CharField(choices=[('lc', 'LC'), ('check', 'Check'), ('tt', 'TT'), ('cash', 'Cash'), ('bank', 'Bank')], default='cash', max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.supplierpurchase')),
            ],
            options={
                'verbose_name': 'Supplier Purchase Payment',
                'verbose_name_plural': 'Supplier Purchase Payments',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
