# Generated by Django 4.2.30 on 2026-08-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_backfill_supplier_purchase_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierpurchasepayment',
            name='method',
            field=models.CharField(choices=[('lc', 'LC'), ('check', 'Cheque'), ('tt', 'TT'), ('cash', 'Cash'), ('bank', 'Bank')], default='cash', max_length=20),
        ),
    ]
